### ISSUE TITLE
Pleease change home page link

### ISSUE THREAD

**Issue by pcav** [gtergeomatica/lidar_tile_maker#1]
It currently points to the issues, not to the repo/readme page.
Thanks.

**Comment by rmarzocchi84** [comment]
I will change it, but what is the difference between tracker and repository?  Obviously I do not understand and I use the link to issuses for tracker because I suppose it is a bug tracking system. 
 
```
tracker=https://github.com/gtergeomatica/lidar_tile_maker/issues
repository=https://github.com/gtergeomatica/lidar_tile_maker
```
Sorry for the stupid question ;-)

**Comment by pcav** [comment]
Please check
http://plugins.qgis.org/plugins/lidar_tile_maker-0_1/
here the link to repo is wrong.
BTW: I would suggest you to change the name of the dir to
http://plugins.qgis.org/plugins/lidar_tile_maker/

**Comment by pcav** [comment]
Better changing it.
Thanks.

**Comment by rmarzocchi84** [comment]
Sorry @pcav probably I need holiday and I do not understand something. 

To change the name of the plugin homepage I download from github the zip file I exctract it to change the name of the folder, re-zip it and upload. Now the name is correct and it is fine. Nevertheless when I try to upload a second version of the plugin I have to do the same process, while for other plugins I have never followed all these steps but only upload a *pluginname-X_X.zip* version. 

What is the difference?

**Comment by pcav** [comment]
didn't you use make zip?
However, this ticket is about home page link, which points to the plugin website, instead of this repo.
Cheers.

**Comment by rmarzocchi84** [comment]
Concerning metadata: 
```
tracker=https://github.com/gtergeomatica/lidar_tile_maker/issues
repository=https://github.com/gtergeomatica/lidar_tile_maker
homepage=https://github.com/gtergeomatica/lidar_tile_maker
```

It is correct?

**Comment by pcav** [comment]
Yes
